/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DispatchIndexRouteImport } from './routes/dispatch/index'
import { Route as PurchaseOrdersIndexRouteImport } from './routes/purchase-orders/index'
import { Route as ReceiptNoticesIndexRouteImport } from './routes/receipt-notices/index'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DispatchIndexRoute = DispatchIndexRouteImport.update({
  id: '/dispatch/',
  path: '/dispatch/',
  getParentRoute: () => rootRouteImport,
} as any)
const PurchaseOrdersIndexRoute = PurchaseOrdersIndexRouteImport.update({
  id: '/purchase-orders/',
  path: '/purchase-orders/',
  getParentRoute: () => rootRouteImport,
} as any)
const ReceiptNoticesIndexRoute = ReceiptNoticesIndexRouteImport.update({
  id: '/receipt-notices/',
  path: '/receipt-notices/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dispatch/': typeof DispatchIndexRoute
  '/purchase-orders/': typeof PurchaseOrdersIndexRoute
  '/receipt-notices/': typeof ReceiptNoticesIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dispatch': typeof DispatchIndexRoute
  '/purchase-orders': typeof PurchaseOrdersIndexRoute
  '/receipt-notices': typeof ReceiptNoticesIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dispatch/': typeof DispatchIndexRoute
  '/purchase-orders/': typeof PurchaseOrdersIndexRoute
  '/receipt-notices/': typeof ReceiptNoticesIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dispatch/'
    | '/purchase-orders/'
    | '/receipt-notices/'
    | '/api/auth/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    '/' | '/dispatch' | '/purchase-orders' | '/receipt-notices' | '/api/auth/$'
  id:
    | '__root__'
    | '/'
    | '/dispatch/'
    | '/purchase-orders/'
    | '/receipt-notices/'
    | '/api/auth/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DispatchIndexRoute: typeof DispatchIndexRoute
  PurchaseOrdersIndexRoute: typeof PurchaseOrdersIndexRoute
  ReceiptNoticesIndexRoute: typeof ReceiptNoticesIndexRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dispatch/': {
      id: '/dispatch/'
      path: '/dispatch'
      fullPath: '/dispatch/'
      preLoaderRoute: typeof DispatchIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/purchase-orders/': {
      id: '/purchase-orders/'
      path: '/purchase-orders'
      fullPath: '/purchase-orders/'
      preLoaderRoute: typeof PurchaseOrdersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/receipt-notices/': {
      id: '/receipt-notices/'
      path: '/receipt-notices'
      fullPath: '/receipt-notices/'
      preLoaderRoute: typeof ReceiptNoticesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DispatchIndexRoute: DispatchIndexRoute,
  PurchaseOrdersIndexRoute: PurchaseOrdersIndexRoute,
  ReceiptNoticesIndexRoute: ReceiptNoticesIndexRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
